### ISSUE TITLE
Can't install this package due to the version of numpy

### ISSUE THREAD

**Issue by CodingCatMountain** [utiasSTARS/graphIK#3]

**Comment by CodingCatMountain** [comment]
I' m sorry. But I have get into trouble when I want to install this package by running:  python3 setup.py install.
My python version is python3.8.10; And it will install the numpy-1.23.0 for me . But the numba will report the error, said numba don't support numpy-1.23. How Can I install this package successfully? Thank You for your help or advise.

**Comment by filipmrc** [comment]
Hey, have you tried installing an earlier version of numpy? I'm using 1.20.1 and it seems to be working.

I will update the setup.py file.

**Comment by CodingCatMountain** [comment]
> Hey, have you tried installing an earlier version of numpy? I'm using 1.20.1 and it seems to be working.
> 
> I will update the setup.py file.

@filipmrc I'm sorry to bother you again, Sir. But Today, I want to install this package in other computer and I failed to install it by ``sudo python3 -m pip install . `` and when it finished, I can only find the ``graphIK-0.1-egg.info`` in my ``/usr/local/lib/python3.8/dist-packages/``. So I compared the ``setup.py`` with other package that I have installed successfully, I found the package name in ``setup.py`` is ``graphIK``  but in this repo, the document  which includes these documents ``graphs``,``robots``,``solvers``and ``utils`` is named by ``graphik`` . So please check the ``setup.py``. Besides, I have touch a empty file named ``__init__.py`` in ``graphik`` documents. After these modification,  I have installed this package successfully.  
I hope my report can help to other people encounter this same problem.
