### ISSUE TITLE
Questions about the figure in the article

### ISSUE THREAD

**Issue by zichunxx** [utiasSTARS/graphIK#4]
Hi! I have read your article and have to admit it is an excellent job!

I am curious about some figures in this article (such as Fig. 1). What software is used to construct the schematic kinematics model?

Hope to get your reply! Thank you!

**Comment by filipmrc** [comment]
Thank you, I'm happy to hear that!

The vector graphics for my figures were done in Inkscape and the LaTeX symbols were added using the Inkscape latex extension (it might come with that by default now).
