### ISSUE TITLE
Cannot find RobotPlanarGraph

### ISSUE THREAD

**Issue by ilefrat** [utiasSTARS/GraphIK#5]
In simple_ik_examples/test_chain_2d_limits_new.py
we have: 
  from graphik.graphs.graph_base import RobotPlanarGraph

However graphik.graphs.graph_base does not contain a RobotPlanarGraph object or function

**Comment by filipmrc** [comment]
Thanks for pointing this out, I will take a look later this week!

**Comment by filipmrc** [comment]
It should work now.
